version: "3.5"

services:
  nginx:
    image: faraks01/teya-chem-frontend-production:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
    networks:
      - teya_local
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  django:
    image: faraks01/teya-chem-backend:01
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - teya_local

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    networks:
      - teya_local
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  etc-letsencrypt:
  webroot-path:

networks:
  teya_local:
    driver: bridge
